### ISSUE TITLE
Use XDG Statdards for cheat directory

### ISSUE THREAD

**Issue by brutus** [chrisallenlane/cheat#142]
I don't like each program to create it's own dot-dir in my home. Why not use the [XDG Stadard](http://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html) instead (afaik it works under windows too)?

With [PyXDG](http://pyxdg.readthedocs.org/) it's easy: https://github.com/brutus/cheat/commit/1296e0fe48d2b227a3bee2bfee7485ba7775157e

This would result in `/home/username/.local/share/cheat` as the default dir under Linux.

**Comment by zed** [comment]
There is also [`appdirs`](https://pypi.python.org/pypi/appdirs/) that is aimed to solve this exact problem e.g., it is used by `pip` (modified).

**Comment by brutus** [comment]
Here's a new pull request based on appdirs: https://github.com/chrisallenlane/cheat/pull/243
