### ISSUE TITLE
Edit system cheatsheet as root

### ISSUE THREAD

**Issue by laomaiweng** [chrisallenlane/cheat#180]
As root, `cheat -e` will happily edit the system-wide cheatsheets in the cheat package, if no customization exists in the DEFAULT_CHEAT_DIR.
It may be a good idea to guard against this (and perhaps add a `--force` flag to ignore this restriction?).

**Comment by chrisallenlane** [comment]
Sorry for the delay on this, guys. This should now be resolved with `cheat` version `2.1.6` :)

If you're interested, here's a link to the relevant diff: https://github.com/chrisallenlane/cheat/commit/c70dc002fa995d7c4a0e134b3b47a187b07589ad

**Comment by chrisallenlane** [comment]
Sorry - better make that `cheat` version `2.1.7`. I realized that `2.1.6` contained a bug after publishing it. It's resolved in `2.1.7`.
