### ISSUE TITLE
Cheat Cheat?

### ISSUE THREAD

**Issue by jamesbiederbeck** [chrisallenlane/cheat#231]
Surely we can include a cheatsheet for cheat.

**Comment by dufferzafar** [comment]
I am not sure if you were kidding, but, here you go: #232 :laughing:

**Comment by chrisallenlane** [comment]
![Mind Blown](http://cloud-4.steamusercontent.com/ugc/39733976193734381/3BC7F6559A807D9BE92FA577A328C83D47D5B9A7/)

Probably not strictly necessary, though :stuck_out_tongue:
