### ISSUE TITLE
syntax highlighting  problem with Csh

### ISSUE THREAD

**Issue by 274914765** [chrisallenlane/cheat#235]
my environment: CentOS 、Csh ， with  environment variable: export CHEATCOLORS=true , but it is not work , please help me , thanks.

**Comment by cnicolov** [comment]
To find out if you've set the env variable properly, type: `setenv | grep CHEATCOLORS`

The proper way of setting this in tcshrc is `echo "setenv CHEATCOLORS true" >> ~/.tcshrc`

**Comment by chrisallenlane** [comment]
@cnicolov is correct. Please also update to the newest version of `cheat` if you haven't. It has changed a lot during the two years it has taken me to reply to this ticket... (Sorry!)
