### ISSUE TITLE
More of a question - is there a similar project using golang?

### ISSUE THREAD

**Issue by ipstone** [chrisallenlane/cheat#248]
it's more of a question, eager to know. 
thanks

**Comment by dufferzafar** [comment]
@ipstone Glad you asked: http://github.com/dufferzafar/cheat

**Comment by ipstone** [comment]
great, thanks! is there a search function implemented or planned? such as:

$cheat emacs -s org-mode
will display the cheatsheet item within emacs with org-mode in the headline?

One general thought I have for the long term would be:
1. more interactive/integration with an editor
2. add a function such as --learn: to cheat --learn url (or text file), to
digest and create some cheat sheets based on the url or the file supplied




On Wed, Dec 23, 2015 at 8:56 PM, Shadab Zafar <notifications@github.com>
wrote:

> @ipstone <https://github.com/ipstone> Glad you asked:
> http://github.com/dufferzafar/cheat <https://github.com/dufferzafar/cheat>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/chrisallenlane/cheat/issues/248#issuecomment-167022641>
> .
>



-- 
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Isaac Xin Pei,
- "A word fitly spoken Is like apples of gold in network of silver. "
Proverbs 25:11

**Comment by chrisallenlane** [comment]
@dufferzafar has you covered :+1: 

@dufferzafar, I merged in your PR referencing your project, since I still haven't gotten around to creating the wiki.
