### ISSUE TITLE
cheat of for/if

### ISSUE THREAD

**Issue by shigemk2** [chrisallenlane/cheat#249]
When writing shell script, I often use "if" or "for".
But I forget the usages of them because OFTEN use them.

So, I want to add if/for on this repository.
Just like this executing "cheat for":
```sh
# loop specified number of times
for i in `seq 1 N`
do
  …
done
```

What do you think about this?

**Comment by chrisallenlane** [comment]
I merged in your PR. Thanks!

**Comment by shigemk2** [comment]
@chrisallenlane 
Thanks for merging my Pull Request :smile: I will create Pull Request for "if" cheatsheet.

**Comment by chrisallenlane** [comment]
:+1:
