### ISSUE TITLE
Add nkf plugin

### ISSUE THREAD

**Issue by shigemk2** [chrisallenlane/cheat#251]
https://en.wikipedia.org/wiki/Network_Kanji_Filter

I don't know this plugin is in demand, but I want to add nkf plugin.

Is this plugin in demand?

**Comment by dufferzafar** [comment]
I have no idea what that filter is or whether it is in demand, but, if you feel that you have a need for that plugin and want to implement it, I don't think you need to worry about whether others have a need for it. Just code it up and create a pull :smile:

**Comment by shigemk2** [comment]
@dufferzafar 
> Just code it up and create a pull
I strong agree. OK, thank you for answering my question.
