### ISSUE TITLE
Partial highlighting in bash

### ISSUE THREAD

**Issue by thecrazy** [chrisallenlane/cheat#255]
Very useful thing you created here.

I was wondering if you had any idea why I would get partial highlighting only.

For example, if I do "cheat tar" the only thing highlighted in the entire output is  *  in red in one of the last examples were it says: --exclude=*

Some other commands like "cheat sed" appear ok.

I include a screenshot bellow, could you let me know if this output is normal?

I am running Xubuntu 15.10 and the options have been set in .bashrc

Thanks you.

![screenshot_2016-01-13_09-45-46](https://cloud.githubusercontent.com/assets/2411956/12297522/8a757c20-b9db-11e5-9f2c-2206696d8f5c.png)

**Comment by lucaswerkmeister** [comment]
Perhaps I’m missing something, but as far as I can see there’s simply nothing more in the `tar` sheet to highlight… no quoted literals, no builtin commands like `echo`, nothing.

It could of course highlight the comments, but it doesn’t do that in the `sed` sheet either, so I don’t think this is a particularly strange bug – just a very plain cheat sheet.

**Comment by thecrazy** [comment]
That would make sense. I guess I was expecting highlighting more similar to what you get using nano.

thx

**Comment by chrisallenlane** [comment]
Sorry it's taken me over a year to get to this! `:facepalm:`

+1 to @lucaswerkmeister's response. The only thing I'll add, though, is that on my system, the comment lines are a different color than the non-comment lines. (Comments are white, text is light gray.) What terminal are you using? Perhaps there are some color settings you can tweak?

**Comment by chrisallenlane** [comment]
FWIW, I'm using `st` with the `solarized-dark` patch applied.
