### ISSUE TITLE
ImportError When I install cheat 

### ISSUE THREAD

**Issue by zhangjh** [chrisallenlane/cheat#258]
$cheat -v
Traceback (most recent call last):
  File "/usr/local/bin/cheat", line 36, in <module>
    from docopt import docopt
ImportError: No module named docopt

**Comment by dufferzafar** [comment]
@zhangjh How did you install cheat?

**Comment by zhangjh** [comment]
1.suod apt-get install python
2.sudo apt-get install python-pip
3.sudo pip install cheat
my os is linux mint 17.3

**Comment by zhangjh** [comment]
o, sorry,I missed this information below...
```
First install the required python dependencies with:

sudo pip install docopt pygments
```
