### ISSUE TITLE
Color output instead of syntax highlighting

### ISSUE THREAD

**Issue by gotbletu** [chrisallenlane/cheat#259]
Can you add color output instead of relying on syntax highlighting?
The syntax highlighting isnt very useful since it only works on very few cheatsheet.
Most of the time, I am seeing all white color text =)

Something like green for commented lines and red for code.
or yellow for commented lines and white for code.

Thanks

**Comment by dufferzafar** [comment]
@gotbletu Have a look at this: https://github.com/dufferzafar/cheat 

It's a go fork of cheat, that I created specifically for the colored output!

**Comment by gotbletu** [comment]
yea i would of used that Go version but they dont got a search option but this python version does =)

**Comment by Liambeguin** [comment]
Hi, 

I use [vimcat](https://github.com/rkitover/vimpager) 
```
function __cheat() {                
if [ $# == 1 ]; then                
    cheat $1 | vimcat -c 'set ft=sh'
else                                
    cheat $@                        
fi                                  
}                                   
alias cheat=__cheat
```

**Comment by gotbletu** [comment]
@Liambeguin  Thanks ill give that a try

**Comment by sogseal** [comment]
@Liambeguin 
Thanks for this! im having issue with the function: __cheat:1: = not found, any idea?

**Comment by Liambeguin** [comment]
Hi, 
is the `__cheat()` function in your bashrc ?

**Comment by sogseal** [comment]
im using zsh but yes, i made it work with just the cheat $1 | vimcat -c 'set ft=sh', but instead of ansi colors i get codes :P

**Comment by Liambeguin** [comment]
hum... I'm not very familiar with zsh but I remember having issues with the colors. 
is your TERM variable correctly set ?

**Comment by sogseal** [comment]
yeah, i think ill move to xterm, i've been having issues with colors. thanks man, dont want to waste more of your time. cheers

**Comment by chrisallenlane** [comment]
Generally speaking, I think the syntax highlighting would work fine for nearly all cheatsheets provided that we defaulted to using a `sh` syntax highlighter. I don't recall what we're doing off the top of my head (I haven't dug into this codebase in a while), but perhaps that would be an easy change.

I'll try to take a look at that this week - unless somebody wants to beat me to the punch with a PR ;)

**Comment by chrisallenlane** [comment]
Color seem OK on my system, so I'm going to assume that @sogseal's local configuration may have been a contributing factor. @sogseal (or anyone else) - if you continue to have trouble on your new terminal, feel free to re-open this ticket. Thanks!
