### ISSUE TITLE
Feature Request: displaying default cheat / displaying your own cheats + the default cheat afterward

### ISSUE THREAD

**Issue by marteaurouge** [chrisallenlane/cheat#262]
When you edit a cheat file, you create a new file including the data from the existing packaged cheat file.

But what happens if there is an update to the default cheat file you already edited, do you have a way to tell some data that may interest you was added? You won't see it because you are displaying your own cheat.

Is it possible maybe to have an option to:
- display the default cheat
- display your own cheat, and below the default cheat (and to be able to change the order)
-  a setting to not use the default cheat data when editing a cheat for the first time

That way if a default cheat is updated you won't miss anything.

**Comment by chrisallenlane** [comment]
Thanks for the input. I agree that this is an issue that needs to be addressed.

I'm going to close this ticket in favor of #322, wherein I propose a solution to this problem. Please read it and leave feedback. Thanks!
