### ISSUE TITLE
How to create N number of records from BE in typo3 6.2?

### ISSUE THREAD

**Issue by PredragMitrovic** [chrisallenlane/cheat#275]
The record has 2 fields:
value - input field,
code - generated string

**Comment by PredragMitrovic** [comment]
so i need to create form, and to have one button witch will give me option for created multiply record,
all that in BE of TYPO3

**Comment by chrisallenlane** [comment]
I'm reasonably confident that you opened this ticket on the wrong repo, so I'm going to close it. Please speak up if I'm mistaken :)
