### ISSUE TITLE
error in cheatsheets crontab ?

### ISSUE THREAD

**Issue by Raizo62** [chrisallenlane/cheat#278]
Hi

I believe that "# every midnight" is more 
      "* 0 * * * /home/user/command.sh"
or
      "0 0 * * * /home/user/command.sh"   ( <--I like it)
than
      "0 * * * * /home/user/command.sh"

no ?

**Comment by chrisallenlane** [comment]
Good catch! I squared that up in the commit linked above.

Thanks!

**Comment by Raizo62** [comment]
Hi

I believe that midnight is more "0 0". I specified "i like it" in front of the line in my last post
I believe that "* 0" is more "midnight and 1 minute", "midnight and 2 minutes", ....
