### ISSUE TITLE
cheat command with other languages

### ISSUE THREAD

**Issue by shigemk2** [chrisallenlane/cheat#279]
I use cheat command, but I sometimes want Japanese cheatsheets.

I think two patterns for cheat command with other languages.

1. Fork this repository and develop forked repository.
2. Use variable $LANG and show Japanese cheatsheet if $LANG is ja_JP.UTF-8.
3. Just use ~/.cheat

Any Ideas?

**Comment by chrisallenlane** [comment]
This **should** already work correctly. For example:

```sh
chris@fourside:~$ cheat -e たとえば
# Inside $EDITOR, type: これは日本語のチートシートです。
chris@fourside:~$ cheat たとえば
これは日本語のチートシートです。
```

I just tested the above on my system, and it worked fine.

Does that work for you? Or am I misunderstanding your goal?

**Comment by chrisallenlane** [comment]
Closing as resolved for now. Please feel free to re-open if necessary.
