### ISSUE TITLE
Very cool!

### ISSUE THREAD

**Issue by SRGOM** [chrisallenlane/cheat#296]
Using it everyday. A minor issue though- I think there is a design issue that once I do a, say, `cheat -e pacman`,  I cannot get new cheatsheets for pacman. I came to know about a lot of cool features of commands I didn't know of so wouldn't like missing out on features in newer versions.

**Comment by sysadmiral** [comment]
It would be nice to have a way to show the package cheatsheets or perhaps merge user cheatsheet with package cheatsheet (giving preference to user sheet obvs).

**Comment by chrisallenlane** [comment]
Thanks for the input, guys.

I'm going to close this ticket in favor of #322, wherein a propose a possible solution. Please read it and give feedback. Thanks!
