### ISSUE TITLE
Searching in specific cheatsheet

### ISSUE THREAD

**Issue by chhsiao90** [chrisallenlane/cheat#307]
Some cheatsheet will contains large content and that would be hard to find specific command in cheatsheet.
For example, if I want to find how I could define proxy server when I'm using httpie,
I could just type ```cheat http -s proxy```, and it would show the match result in the specific cheatsheet that I need.

Thanks!

**Comment by chrisallenlane** [comment]
In this case, I would recommend utilizing the existing shell tools to do this in a more "unix-y" way.

For example:

```sh
cheat http | grep proxy
```

Or maybe:

```sh
cheat http | less
# then manually search (/) for "proxy"
```

Make sense?
