### ISSUE TITLE
Continually needing to run $ export CHEAT_EDITOR="vim"

### ISSUE THREAD

**Issue by alteredtastes** [chrisallenlane/cheat#319]
I am consistently running into message:
```You must set a CHEAT_EDITOR, VISUAL, or EDITOR environment variable in order to create/edit a cheatsheet.```

when I run `cheat -e {cheat-name}`.

I've run `$ export CHEAT_EDITOR="vim"` multiple times today. Suggestions to resolve? Running commands from oh-my-zsh 5.3.1.

**Comment by chrisallenlane** [comment]
This really isn't a `cheat` issue, but pertains to the behavior of the shell in general.

When you run `export` in a shell, the exported variable only persists until the shell is closed. If you want to export a variable in a more "permanent" way, you must do so from within your `~/.profile`, `~/.bash_profile`, or `~/.bashrc` file, depending on the details of how your system is configured. (If you're running a Debian derivative, you'll probably want to modify `~/.bash_profile`.)

This link should get you started:
https://unix.stackexchange.com/questions/21598/how-do-i-set-a-user-environment-variable-permanently-not-session
