### ISSUE TITLE
ImportError: No module named docopt

### ISSUE THREAD

**Issue by woshixieming** [chrisallenlane/cheat#345]
[root@localhost cheat]# cheat -v
Traceback (most recent call last):
  File "/usr/bin/cheat", line 40, in <module>
    from docopt import docopt
ImportError: No module named docopt

**Comment by woshixieming** [comment]
It's already working。
```
sudo pip install docopt pygments
```

**Comment by chrisallenlane** [comment]
Sorry for the delay, and I'm glad you got it figured out. I'll take a second look at the documentation to see if I can make the dependency documentation any clearer.

Closing as resolved.
