### ISSUE TITLE
v in tag name 2.2.1

### ISSUE THREAD

**Issue by ilovezfs** [chrisallenlane/cheat#348]
Did you intend the tag to be named v2.2.1 not 2.2.1?

**Comment by chrisallenlane** [comment]
I did not. That was a convention that I absent-mindedly carried over from nodejs world. I just deleted the `v2.2.1` release and published a new `2.2.1` release in its place.

Thanks for bringing this to my attention.

**Comment by ilovezfs** [comment]
no problem :)
