### ISSUE TITLE
Add an option for case-insensitive search

### ISSUE THREAD

**Issue by tculp** [chrisallenlane/cheat#397]
Searches for terms often make sense to be case-insensitive. For example, searches for ssh, SSH, Ssh, etc. all return different results.

It would be useful to have an option for case-insensitive search, or to make it the default behavior.

**Comment by chrisallenlane** [comment]
Geez - I never even noticed that the search was case-sensitive. That's a considerable oversight on my part.

In my opinion, case-sensitive search really isn't useful for `cheat`'s use-case. What is your (and everyone's) opinion on perhaps simply making `-s` case-insensitive entirely, thus obviating the need for a distinct `-S` option?

**Comment by tculp** [comment]
I would be fine with changing the default behavior to be case-insensitive, and I would actually prefer that to be the case. We could also easily switch -s and -S, so -S is case-sensitive and -s is insensitive, since I can see potential (though uncommon) uses for case-sensitivity

**Comment by tculp** [comment]
Any update on this?

**Comment by tculp** [comment]
Bump

**Comment by chrisallenlane** [comment]
I'm closing this as it was resolved by #399. (Thanks, @tculp!) I'll publish a new `minor` release shortly.
