### ISSUE TITLE
can I use this in vim?

### ISSUE THREAD

**Issue by zhaochy1990** [chrisallenlane/cheat#405]
Is there any vim plugin that can integrate this to vim?

SO, I can use this inside the editor, and won't need to go back to cmd line once and once...

**Comment by chrisallenlane** [comment]
There are no specific plugins, to my knowledge.

You probably don't need one, though. Recall that you can use `!` to execute shell commands from within vim.

For example, to view the output of `cheat tar` within vim, you can just do the following:

    :!cheat tar

If you're using a terminal version of vim, note that you can also background your editor by pressing `ctrl+z`, use `cheat` from the shell, and then return your editor to the foreground with `fg`. That's usually what I do.
